CardSort.WebUI/Models/CardsListViewModel.cs
using System.Collections.Generic;
using CardSort.Domain.Entities;

namespace CardSort.WebUI.Models
{
    public class CardsListViewModel
    {
        public IEnumerable<Card> Cards { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

CardSort.WebUI/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CardSort.WebUI.Models
{
    public class LoginViewModel
    {
        [Required]
        public string UserName { get; set; }
        [Required]
        public string Password { get; set; }
    }
}

CardSort.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CardSort.WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages
        { 
            get
            {
                return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage);
            }
        }
    }
}

CardSort.WebUI/Controllers/AccountController.cs
using System.Web.Mvc;
using CardSort.WebUI.Models;
using CardSort.WebUI.Infrastructure.Abstract;

namespace CardSort.WebUI.Controllers
{
    public class AccountController : Controller
    {
        IAuthProvider authProvider;
        public AccountController(IAuthProvider auth)
        {
            authProvider = auth;
        }

        public ViewResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                if (authProvider.Authenticate(model.UserName, model.Password))
                {
                    return Redirect(returnUrl ?? Url.Action("Index", "Admin"));
                }
                else
                {
                    ModelState.AddModelError("", "Incorrect username or password");
                    return View();
                }
            }
            else
            {
                return View();
            }
        }
    }
}

CardSort.WebUI/Controllers/AdminController.cs
using System.Web.Mvc;
using CardSort.Domain.Abstract;
using System.Linq;
using CardSort.Domain.Entities;
using System.Web;

namespace CardSort.WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private ICardRepository repository;

        public AdminController(ICardRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index()
        {
            return View(repository.Cards);
        }

        public ViewResult Edit (int cardID)
        {
            Card card = repository.Cards.FirstOrDefault(c => c.CardID == cardID);
            return View(card);
        }

        [HttpPost]
        public ActionResult Edit(Card card, HttpPostedFileBase image=null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    card.ImageMimeType = image.ContentType;
                    card.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(card.ImageData, 0, image.ContentLength);
                }
                repository.SaveCard(card);
                TempData["message"] = string.Format("{0} has been saved.", card.Name);
                return RedirectToAction("Index");
            }
            else
            {
                return View(card);
            }
        }

        public ViewResult Create()
        {
            ViewBag.operation = "create";
            return View("Edit", new Card());
        }

        [HttpPost]
        public ActionResult Delete(int cardID)
        {
            Card deletedCard = repository.DeleteCard(cardID);
            if (deletedCard != null)
            {
                TempData["message"] = string.Format("{0} was deleted.", deletedCard.Name);
            }
            return RedirectToAction("Index");
        }

    }
}

CardSort.WebUI/Controllers/CardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CardSort.Domain.Abstract;
using CardSort.WebUI.Models;
using CardSort.Domain.Entities;

namespace CardSort.WebUI.Controllers
{
    public class CardController : Controller
    {
       private ICardRepository myrepository;

        public CardController (ICardRepository myrepository)
        {
            this.myrepository = myrepository;
        }

        public int PageSize = 4;
        public ViewResult List(string category, int page = 1)
        {
            CardsListViewModel model = new CardsListViewModel
            {
                Cards = myrepository.Cards.Where(c => category == null || c.CardType == category).OrderBy(c => c.CardID).Skip((page - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    //TotalItems = myrepository.Cards.Count()
                    TotalItems = category == null? myrepository.Cards.Count() : myrepository.Cards.Where(e => e.CardType == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }

        public FileContentResult GetImage(int cardId)
        {
            Card card = myrepository.Cards.FirstOrDefault(c => c.CardID == cardId);

            if (card != null)
            {
                return File(card.ImageData, card.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

CardSort.WebUI/Controllers/NavController.cs
using CardSort.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CardSort.WebUI.Controllers
{
    public class NavController : Controller
    {
        private ICardRepository repository;

        public NavController (ICardRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.Cards.Select(c => c.CardType).Distinct().OrderBy(c => c);

            return PartialView(categories);
        }
    }
}

CardSort.WebUI/Views/Admin/Edit.cshtml
@model CardSort.Domain.Entities.Card

@{
    var operationText = "";
    if(ViewBag.operation == "create") {
        operationText = "Enter a new Card";
    }
    else {
        operationText = "Edit " + @Model.Name;
    }

    ViewBag.Title = operationText;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h2>@operationText</h2>
    </div>

    @using (Html.BeginForm("Edit", "Admin", FormMethod.Post, new {enctype = "multipart/form-data"}))
    {
        <div class="card-body">
            @Html.HiddenFor(m => m.CardID)

            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                switch (property.PropertyName)
                {
                    case "CardID":
                    case "ImageData":
                    case "ImageMimeType":
                        break;
                    default:
                        <div class="mb-3">
                            <label class="form-label">
                                @(property.DisplayName ?? property.PropertyName)
                            </label>

                            @*@if (property.PropertyName == "Description")
                            {
                                @Html.TextArea(property.PropertyName, null, new { @class = "form-control", rows = 5 })
                            }
                            else
                            {
                                @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                            }*@

                            @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })

                            @Html.ValidationMessage(property.PropertyName)

                        </div>
                        break;
                }
            }

            <div class="mb-3">
                <label class="form-label">Image</label>
                <div style="position:relative;">
                    <a class="btn btn-secondary" href="javascript:;">
                        Choose File
                        <input type="file" name="Image" size="40" style="position:absolute; z-index:2; top:0; left:0; opacity:0; background-color:transparent; color:transparent;" onchange='$("#upload-file-info").html($(this).val());' />
                    </a>
                    <span class="form-label label-info" id="upload-file-info"></span>
                </div>

                @if(Model.ImageData == null)
                {
                    <div class="form-text">No Image</div>
                }
                else
                {
                    <img class="img-thumbnail" width="150" height="150" src='@Url.Action("GetImage","Card", new {Model.CardID})' />
                }
            </div>
        </div>

        <div class="card-footer">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Cancel and return to list", "Index", null, new {@class = "btn btn-secondary"})
        </div>
    }
</div>

CardSort.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<CardSort.Domain.Entities.Card>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h3>All Cards</h3>
        @Html.ActionLink("Enter a new card", "Create", null, new { @class = "btn btn-primary" })
    </div>

    <div class="card-body">
        @*<table class="table table-striped table-condensed table-bordered">*@
        <div class="float-right search btn-group">
            <input class="form-control search-input" type="search" aria-label="Search" placeholder="Search" autocomplete="off" id="myInput">
        </div>
        
        <table data-toggle="table" data-pagination="true" data-serach="true" id="table">
            <thead>
                <tr>
                    <th data-sortable="true" data-field="name" data-searchable="true">
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th data-sortable="true">
                        @Html.DisplayNameFor(model => model.Colors)
                    </th>
                    <th data-sortable="true">
                        @Html.DisplayNameFor(model => model.CardType)
                    </th>
                    <th data-sortable="true">
                        @Html.DisplayNameFor(model => model.SetCode)
                    </th>
                    <th data-sortable="true">
                        @Html.DisplayNameFor(model => model.CollectorNumber)
                    </th>
                    <th data-sortable="true">
                        @Html.DisplayNameFor(model => model.ArtistName)
                    </th>
                    <th>Actions</th>
                </tr>
            </thead>

            <tbody id="myTable">
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.ActionLink(item.Name, "Edit", new { item.CardID })</td>
                        <td>@item.Colors</td>
                        <td>@item.CardType</td>
                        <td>@item.SetCode</td>
                        <td>@item.CollectorNumber</td>
                        <td>@item.ArtistName</td>
                        <td class="text-center">
                            @using (Html.BeginForm("Delete", "Admin"))
                            {
                                @Html.Hidden("CardID", item.CardID)
                                <input type="submit"
                                       class="btn btn-primary"
                                       value="Delete" />
                            }
                        </td>
                    </tr>
                }
            </tbody>
            

        </table>

    </div>
</div>

<script>
    $(document).ready(function () {
        $("#myInput").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>

CardSort.WebUI/Views/Card/List.cshtml
@model CardSort.WebUI.Models.CardsListViewModel

@{
    ViewBag.Title = "Cards";
}

@foreach (var c in Model.Cards)
{
    @Html.Partial("CardSummary", c)
}

<div>
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new {page = x}))
</div>

CardSort.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Home", "List", "Card", null, new { @class = "btn btn-outline-secondary w-100 btn-lg mb-2" })

@foreach(var link in Model)
{
    @Html.RouteLink(link, new {
        controller = "Card",
        action = "List",
        category = link,
        page = 1 },
    new {@class = "btn btn-outline-secondary w-100 btn-lg mb-2" + (link == ViewBag.SelectedCategory ? " active" : "")})
}

CardSort.WebUI/Views/Shared/CardSummary.cshtml
@model CardSort.Domain.Entities.Card

<div class="card p-3 bg-light text-dark mb-2">



    <h3>
        <strong>@Model.Name</strong>
        <span class="badge bg-primary float-end">
            @Model.Colors
        </span>
    </h3>
    <span class="lead">@Model.CardType</span>
    @if (Model.ImageData != null)
    {
        <div class="pull-left" style="margin-right: 10px">
            <img src="@Url.Action("GetImage", "Card", new {Model.CardID})" />
        </div>
    }
</div>

CardSort.WebUI/Views/Shared/_AdminLayout.cshtml
@{ 
    Layout = null;
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-table@1.24.1/dist/bootstrap-table.min.css">

    <script src="~/Scripts/jquery-1.4.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-table@1.24.1/dist/bootstrap-table.min.js"></script>

    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">
                @TempData["message"]
            </div>
        }
        @RenderBody()
    </div>
</body>
</html>

CardSort.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>

<body>
    <div class="navbar navbar-dark bg-dark">
    <a class="navbar-brand ms-4" href="#">CARD SORT</a>
    <a class="nav-item ms-4 btn btn-primary" href="/Admin/Index">Edit Collection</a>z
    </div>

    <div class="row border p-3">
        <div id="categories" class="col-3">
            @Html.Action("Menu", "Nav")
        </div>

        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>